<a href="https://colab.research.google.com/github/sokim0991/Beginner-Intro-to-Neural-Networks/blob/main/softmax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

def softmax(a):
  exp_a = np.exp(all)
  sum_exp_a = np.sum(exp_a)
  y = exp_a / sum_exp_a
    
  return y

In [ ]:
a = np.array([0.3,2.9,4.0])
exp_a = np.exp(a)
sum_exp_a = np.sum(exp_a)
y = exp_a / sum_exp_a

In [ ]:
print(a)

[0.3 2.9 4. ]


In [ ]:
print(exp_a)

[ 1.34985881 18.17414537 54.59815003]


In [ ]:
print(sum_exp_a)

74.1221542101633


In [ ]:
print(y)

[0.01821127 0.24519181 0.73659691]


In [ ]:
print(sum(y))

1.0


Softmax는 Overflow에 취약하다. 수식에 e^x 들어가기 때문에 Overflow 범위를 넘어설 수 있다. 이를 해결하기 위해서는 Softmax의 성질을 이용한다.


In [ ]:
a = np.array([1010, 1000, 990]) 
print(np.exp(a) / np.sum(np.exp(a)))

[nan nan nan]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


In [ ]:
c = np.max(a)

In [ ]:
print(a-c)

[  0 -10 -20]


In [ ]:
def new_softmax(a) : 
    c = np.max(a) # 최댓값
    exp_a = np.exp(a-c) # 각각의 원소에 최댓값을 뺀 값에 exp를 취한다. (이를 통해 overflow 방지)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y